version: "3.8"
services:
  back:
    restart: always
    container_name: info-gu-back
    image: ${IMAGE}
    ports:
        - "0.0.0.0:8080:8080"
    networks:
      - custom

  postgres:
    container_name: info-gu-db
    image: 'postgres:16.0'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_NAME -d $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - custom

networks:
    custom:
      driver: bridge
